/** Reusable field layouts for `sheet` template pages. */
const F = (key, label, type = "text") => ({ key, label, type });
const OBS_HEADER_FIELDS = [
  F("sampleCode", "Sample code / job order no."),
  F("sampleDescription", "Sample description"),
  F("envTemp", "Environmental temp."),
  F("envHumidity", "Environmental humidity"),
  F("testStart", "Date of testing start"),
  F("testEnd", "Date of testing end"),
  F("refStandardMethod", "Ref. standard / test method"),
  F("equipmentUsed", "Equipment used (Equip. ID)", "textarea"),
];

export const SHEET_PRESETS = {
  generic_8_6: {
    headerFields: Array.from({ length: 8 }, (_, i) => F(`h${i + 1}`, `Parameter ${i + 1}`)),
    rowFields: Array.from({ length: 6 }, (_, i) => F(`c${i + 1}`, `Value ${i + 1}`)),
  },
  outdoor_17: {
    headerFields: [
      F("exposureSite", "Exposure site / location"),
      F("mounting", "Mounting / tilt / azimuth"),
      F("startDate", "Exposure start date"),
      F("endDate", "Exposure end date"),
      F("irradiation", "Cumulative irradiation (kWh/m²)"),
      F("irradianceRef", "Reference irradiance / sensor"),
      F("ambientRange", "Ambient temperature range [°C]"),
      F("moduleTempRange", "Module temperature range [°C]"),
      F("measuredSide", "Measured side (front / back)"),
      F("soilingNotes", "Soiling / cleaning notes"),
      F("pyranometerCalibrated", "Pyranometer / reference calibrated", "checkbox"),
      F("moduleCleaned", "Module surface cleaned before test", "checkbox"),
    ],
    rowFields: [
      F("sampleNo", "Sample #"),
      F("visualFindings", "Visual after exposure (findings / photo ref)"),
      F("powerNote", "Power / EL note (if applicable)"),
      F("remarks", "Remarks"),
    ],
  },
  /** Each + Row repeats the full thermal test block (per IEC table 09 layout). */
  bypass_18: {
    headerFields: [F("moduleSerial", "Module / sample ID (optional header)")],
    rowFields: [
      F("moduleTemp", "Module temperature [°C]"),
      F("diodeCount", "Number of diodes in junction box"),
      F("diodeMfr", "Diode manufacturer"),
      F("diodeType", "Diode type designation"),
      F("tjmax", "TJmax [°C] (datasheet)"),
      F("prepProcedure", "Sample preparation procedure"),
      F("amb1", "Ambient temp. junction box (step 1)"),
      F("pulse1", "Pulsed current (step 1)"),
      F("vd1", "Voltage drop VD [V] (step 1)"),
      F("vdchar1", "VD vs TJ characteristic (step 1)"),
      F("amb2", "Ambient temp. junction box (step 2)"),
      F("pulse2", "Pulsed current (step 2)"),
      F("vd2", "Voltage drop VD [V] (step 2)"),
      F("vdchar2", "VD vs TJ characteristic (step 2)"),
      F("amb3", "Ambient temp. junction box (step 3)"),
      F("pulse3", "Pulsed current (step 3)"),
      F("vd3", "Voltage drop VD [V] (step 3)"),
      F("vdchar3", "VD vs TJ characteristic (step 3)"),
      F("notes", "Additional notes / results"),
    ],
  },
  /**
   * PDF page 19 — Step 2 bypass diode thermal test (PEL sheet): every field repeats per + Row.
   */
  bypass_19: {
    headerFields: [F("moduleSerial", "Module / sample ID (optional header)")],
    rowFields: [
      F("vd", "Voltage drop, VD [V]"),
      F("vdVsTj", "VD versus TJ characteristic", "textarea"),
      F(
        "tjmaxDatasheet",
        "Max. permissible junction temperature TJmax [°C] (according to diode datasheet)",
      ),
      F("currentFlowApplied", "Current flow applied [A]"),
      F("tjMaxSurfaceAllowed", "Max. diode surface temperature allowed Tj max [°C]"),
      F("vdAfter1h", "Voltage drop, VD [V] after 1 h"),
      F("tjcalc", "Calculated max. junction temperature Tjcalc [°C]"),
      F("tjcalcPassYes", "TJcalc < TJmax (test passed)? — Yes", "checkbox"),
      F("tjcalcPassNo", "TJcalc < TJmax (test passed)? — No", "checkbox"),
      F("currentFlow125Isc", "Current flow (1.25 × Isc) [A]"),
      F("bypassFunctionalYes", "Bypass diode remain(s) functional — Yes", "checkbox"),
      F("bypassFunctionalNo", "Bypass diode remain(s) functional — No", "checkbox"),
      F("remarks", "Remarks", "textarea"),
    ],
  },
  /**
   * PDF page 21 uses custom multi-table form (`ObservationFormSheetTable10Page21`), not generic rows.
   */
  table10_page21: {
    headerFields: [],
    rowFields: [],
  },
  /**
   * PDF page 22 uses custom WBT grid form (`ObservationFormHotSpotPage22`), not generic rows.
   */
  hot_spot_22: {
    headerFields: [],
    rowFields: [],
  },
  mechanical_28: {
    headerFields: [
      F("moduleTemp", "Temperature of tested module [°C]"),
      F("maxPressure", "Maximum pressure [Pa]"),
      F("pressureTol", "Pressure tolerance [Pa]"),
      F("monitorCurrent", "Monitoring current [A]"),
      F("ratePerMin", "Rate per minute (cycles)"),
      F("numCycles", "Number of cycles"),
      F("pressureProvider", "Pressure provider (air / vacuum)"),
      F("cellBroken", "Cell / live part broken (Y/N)"),
      F("currentContinuous", "Current continuous / disconnection"),
    ],
    rowFields: [
      F("sampleNo", "Sample #"),
      F("cycleNote", "Cycle / phase notes"),
      F("result", "Result"),
    ],
  },
  uv_26: {
    headerFields: [
      F("testMethod", "Test method / conditions"),
      F("irradiance", "Total UV irradiation [kWh/m²]"),
      F("moduleTemp", "Module temperature [°C]"),
    ],
    rowFields: [
      F("sampleNo", "Sample #"),
      F("side", "Frontside / Backside"),
      F("result", "Result / remarks"),
    ],
  },
  combo_visual_wet: {
    headerFields: [
      F("testVoltage", "Test voltage applied [V]"),
      F("solutionTemp", "Solution temperature [°C]"),
      F("solutionRes", "Solution resistivity [Ω·cm]"),
      F("moduleSize", "Size of module [m²]"),
    ],
    rowFields: [
      F("sampleNo", "Sample #"),
      F("col2", "Measured / findings"),
      F("col3", "Limit / required"),
      F("result", "Result"),
    ],
  },
  /** PDF pages 23–29 — custom multi-section forms; `rowFields` unused. */
  page_23_hs_visual_stc: { headerFields: [], rowFields: [] },
  page_24_bnpi_insulation: { headerFields: [], rowFields: [] },
  page_25_wet_bypass_hs: { headerFields: [], rowFields: [] },
  page_26_uv_front_back: { headerFields: [], rowFields: [] },
  page_27_uv_followup: { headerFields: [], rowFields: [] },
  page_28_mech_combo: { headerFields: [], rowFields: [] },
  page_29_tc50_visual: { headerFields: [], rowFields: [] },
  page_31_hf10_combo: { headerFields: [], rowFields: [] },
  page_32_jbox_combo: { headerFields: [], rowFields: [] },
  page_33_tc200_visual: { headerFields: [], rowFields: [] },
  page_35_damp_heat_combo: { headerFields: [], rowFields: [] },
  page_36_static_mech_combo: { headerFields: [], rowFields: [] },
  page_37_hail_combo: { headerFields: [], rowFields: [] },
  page_38_pid_combo: { headerFields: [], rowFields: [] },
  page_40_final_stab_233: { headerFields: [], rowFields: [] },
  page_41_final_stab_234: { headerFields: [], rowFields: [] },
  page_42_stc_front_236: { headerFields: [], rowFields: [] },
  page_43_stc_back_237: { headerFields: [], rowFields: [] },
  page_44_bnpi_final_238: { headerFields: [], rowFields: [] },
  page_47_a41_front: { headerFields: [], rowFields: [] },
  page_48_a44_back: { headerFields: [], rowFields: [] },
  page_49_a43_bnpi: { headerFields: [], rowFields: [] },
  page_50_a47_ini: { headerFields: [], rowFields: [] },
  page_52_a47_stc_front: { headerFields: [], rowFields: [] },
  page_53_a48_back: { headerFields: [], rowFields: [] },
  page_54_a49_bnpi: { headerFields: [], rowFields: [] },
  svc_10322_creepage_clearance: {
    headerFields: OBS_HEADER_FIELDS,
    rowFields: [
      F("clauseNo", "Clause no."),
      F("testRequirement", "Test / requirement"),
      F("testObservation", "Test result / observation", "textarea"),
    ],
  },
  svc_10322_endurance_thermal: {
    headerFields: OBS_HEADER_FIELDS,
    rowFields: [
      F("clauseNo", "Clause no."),
      F("enduranceItem", "Endurance / thermal test item"),
      F("valueObserved", "Value / observation", "textarea"),
    ],
  },
  svc_10322_humidity_insulation: {
    headerFields: OBS_HEADER_FIELDS,
    rowFields: [
      F("section", "Section / clause"),
      F("parameter", "Parameter"),
      F("measurement", "Measured value / result"),
      F("remarks", "Remarks", "textarea"),
    ],
  },
  svc_10322_earthing: {
    headerFields: OBS_HEADER_FIELDS,
    rowFields: [
      F("clauseNo", "Clause no."),
      F("requirement", "Requirement"),
      F("measuredResistance", "Measured resistance"),
      F("result", "Result"),
    ],
  },
  svc_10322_heat_fire_tracking: {
    headerFields: OBS_HEADER_FIELDS,
    rowFields: [
      F("clauseNo", "Clause no."),
      F("testName", "Test name"),
      F("partTested", "Part tested"),
      F("testTemp", "Test temperature"),
      F("observation", "Observation / result", "textarea"),
    ],
  },
  svc_10322_temperature_measurement: {
    headerFields: OBS_HEADER_FIELDS,
    rowFields: [
      F("part", "Part"),
      F("normalTest1", "Clause 12.4 normal - test 1"),
      F("normalTest2", "Clause 12.4 normal - test 2"),
      F("limit", "Limit"),
      F("remarks", "Remarks"),
    ],
  },
  svc_15885_creepage_clearance: {
    headerFields: OBS_HEADER_FIELDS,
    rowFields: [
      F("section", "Section"),
      F("measurementPoint", "Measurement point"),
      F("requiredAt50V", "Required @50 V"),
      F("measuredAt50V", "Measured @50 V"),
      F("requiredAt150V", "Required @150 V"),
      F("measuredAt150V", "Measured @150 V"),
      F("requiredAt250V", "Required @250 V"),
      F("measuredAt250V", "Measured @250 V"),
      F("requiredAt500V", "Required @500 V"),
      F("measuredAt500V", "Measured @500 V"),
      F("requiredAt750V", "Required @750 V"),
      F("measuredAt750V", "Measured @750 V"),
      F("requiredAt1000V", "Required @1000 V"),
      F("measuredAt1000V", "Measured @1000 V"),
      F("result", "Result / remarks", "textarea"),
    ],
    footerFields: [
      F("testedBySign", "Tested by - Sign"),
      F("testedByName", "Tested by - Name"),
      F("testedByDate", "Tested by - Date"),
      F("checkedBySign", "Checked by - Sign"),
      F("checkedByName", "Checked by - Name"),
      F("checkedByDate", "Checked by - Date"),
    ],
  },
  svc_15885_electric_strength: {
    headerFields: OBS_HEADER_FIELDS,
    rowFields: [
      F("clauseNo", "Clause no."),
      F("testCondition", "Test condition"),
      F("workingVoltage", "Working voltage"),
      F("appliedTestVoltage", "Applied test voltage"),
      F("requirement", "Requirement"),
      F("result", "Result / observation"),
      F("remarks", "Remarks"),
    ],
    footerFields: [
      F("testedBySign", "Tested by - Sign"),
      F("testedByName", "Tested by - Name"),
      F("testedByDate", "Tested by - Date"),
      F("checkedBySign", "Checked by - Sign"),
      F("checkedByName", "Checked by - Name"),
      F("checkedByDate", "Checked by - Date"),
    ],
  },
  svc_15885_moisture_insulation: {
    headerFields: OBS_HEADER_FIELDS,
    rowFields: [
      F("clauseNo", "Clause no."),
      F("testCondition", "Test condition"),
      F("humidityCondition", "Humidity condition"),
      F("testVoltageDc", "Insulation test voltage (DC)"),
      F("requiredInsulation", "Required insulation (MΩ)"),
      F("measuredInsulation", "Measured insulation (MΩ)"),
      F("result", "Result"),
      F("remarks", "Remarks"),
    ],
    footerFields: [
      F("testedBySign", "Tested by - Sign"),
      F("testedByName", "Tested by - Name"),
      F("testedByDate", "Tested by - Date"),
      F("checkedBySign", "Checked by - Sign"),
      F("checkedByName", "Checked by - Name"),
      F("checkedByDate", "Checked by - Date"),
    ],
  },
  svc_15885_heat_fire_tracking: {
    headerFields: OBS_HEADER_FIELDS,
    rowFields: [
      F("clauseNo", "Clause no."),
      F("testName", "Test name"),
      F("partTested", "Part tested"),
      F("testTempOrDuration", "Test temp. / duration"),
      F("observation", "Observation / result", "textarea"),
      F("result", "Pass / fail"),
      F("remarks", "Remarks"),
    ],
    footerFields: [
      F("testedBySign", "Tested by - Sign"),
      F("testedByName", "Tested by - Name"),
      F("testedByDate", "Tested by - Date"),
      F("checkedBySign", "Checked by - Sign"),
      F("checkedByName", "Checked by - Name"),
      F("checkedByDate", "Checked by - Date"),
    ],
  },
  svc_16102_cap_temperature_rise: {
    headerFields: OBS_HEADER_FIELDS,
    rowFields: [
      F("clauseNo", "Clause no."),
      F("requirement", "Requirement"),
      F("measuredRiseK", "Measured cap temperature rise (K)"),
      F("limitK", "Limit (K)"),
      F("result", "Result"),
    ],
  },
  svc_16102_creepage_clearance: {
    headerFields: OBS_HEADER_FIELDS,
    rowFields: [
      F("measurementPoint", "Measurement point"),
      F("upVoltage", "UP (V)"),
      F("urmsVoltage", "Urms (V)"),
      F("requiredCl", "Required cl (mm)"),
      F("measuredCl", "Measured cl (mm)"),
      F("requiredCr", "Required cr (mm)"),
      F("measuredCr", "Measured cr (mm)"),
    ],
  },
  svc_16102_insulation_electric_strength: {
    headerFields: OBS_HEADER_FIELDS,
    rowFields: [
      F("clauseNo", "Clause no."),
      F("testName", "Test name"),
      F("testCondition", "Condition"),
      F("requiredValue", "Required value"),
      F("measuredValue", "Measured value"),
      F("result", "Result"),
    ],
  },
  svc_16102_heat_fire_tracking: {
    headerFields: OBS_HEADER_FIELDS,
    rowFields: [
      F("clauseNo", "Clause no."),
      F("testName", "Test name"),
      F("partTested", "Part tested"),
      F("testTemperature", "Test temperature"),
      F("flameExtinguishTime", "Time to self-extinguish"),
      F("observation", "Observation / result"),
    ],
  },
  svc_16103_electric_strength: {
    headerFields: OBS_HEADER_FIELDS,
    rowFields: [
      F("clauseNo", "Clause no."),
      F("testCondition", "Test condition"),
      F("testVoltage", "Test voltage"),
      F("result", "Result / observation"),
    ],
  },
  svc_16103_moisture_insulation: {
    headerFields: OBS_HEADER_FIELDS,
    rowFields: [
      F("clauseNo", "Clause no."),
      F("testCondition", "Test condition"),
      F("requiredInsulation", "Required insulation (MΩ)"),
      F("measuredInsulation", "Measured insulation (MΩ)"),
      F("result", "Result"),
    ],
  },
  svc_16103_heat_fire_tracking: {
    headerFields: OBS_HEADER_FIELDS,
    rowFields: [
      F("clauseNo", "Clause no."),
      F("testName", "Test name"),
      F("partTested", "Part tested"),
      F("testTempOrDuration", "Test temp. / duration"),
      F("observation", "Observation / result", "textarea"),
    ],
  },
};
